### PR TITLE
Feat: add image crop project

### PR DESCRIPTION
**Pull request by Ayushjhawar8**

### CODE REVIEW

**Comment by Tpuljak** [comment]
@Ayushjhawar8 please add a sign off to the commit

**Comment by Ayushjhawar8** [comment]
> @Ayushjhawar8 please add a sign off to the commit

yes im learning how to do that 😅

**Comment by Tpuljak** [comment]
@Ayushjhawar8 you can do this:

```
git rebase HEAD~1 --signoff
git push -f
```

**Comment by Ayushjhawar8** [comment]
> @Ayushjhawar8 you can do this:
> 
> ```
> git rebase HEAD~1 --signoff
> git push -f
> ```

please check

**Pull request merged**
